### PR TITLE
Add mappings descriptions

### PR DESCRIPTION
**Pull request by Arkanayan**
Add key map descriptions, so it shows up in which key and other places.

### CODE REVIEW

**Comment by mikebcbc** [comment]
This would be great to merge - would fix integration with mini.nvim as well. Adding my 2 cents to review as it looks good & simple enough.

**Review by mikebcbc — APPROVED** [review]

**Comment by Arkanayan** [comment]
Thanks for the review, @mikebcbc. Could you please merge this?

**Comment by mikebcbc** [comment]
> Thanks for the review, @mikebcbc. Could you please merge this?

I would love to, but I’m not a maintainer of the project! Just throwing in my two cents as a 3rd party reviewer!

**Comment by otavioschwanck** [comment]
Thanks!

**Pull request merged**
