### PR TITLE
feat: basic integrate with portal

### PR DESCRIPTION
**Pull request by xzbdmw**
I tried using the callback of portal's context directly to delete the bookmark, which can achieve deletion but without any visual effect. The deleted window will still be displayed. Implementing the delete mode in portal ui may require changing portal's API, or should we have the same look as files for managing bookmarks(portal only for jumping)?

### CODE REVIEW

**Comment by otavioschwanck** [comment]
> I tried using the callback of portal's context directly to delete the bookmark, which can achieve deletion but without any visual effect. The deleted window will still be displayed. Implementing the delete mode in portal ui may require changing portal's API, or should we have the same look as files for managing bookmarks(portal only for jumping)?

we could just refresh the portal after deleting something.  Maybe will have some blink, but its ok for now

**Comment by otavioschwanck** [comment]
also, when i try to open the preview:

E5108: Error executing lua: /Users/./Projetos/arrow.nvim/lua/arrow/buffer_ui.lua:82: attempt to call field 'preview' (a nil value)
stack traceback:
        /Users/./Projetos/arrow.nvim/lua/arrow/buffer_ui.lua:82: in function </Users/./Projetos/arrow.nvim/lua/arrow/buffer_ui.lua:73>

For some reason, my portal doesn't implement preview:
:lua = require("portal")
{
  initialize = <function 1>,
  search = <function 2>,
  setup = <function 3>,
  tunnel = <function 4>
}

**Comment by xzbdmw** [comment]
Oh, forget I changed their code

**Comment by xzbdmw** [comment]
Now should works

**Comment by xzbdmw** [comment]
> > I tried using the callback of portal's context directly to delete the bookmark, which can achieve deletion but without any visual effect. The deleted window will still be displayed. Implementing the delete mode in portal ui may require changing portal's API, or should we have the same look as files for managing bookmarks(portal only for jumping)?
> 
> we could just refresh the portal after deleting something (close and open again). Maybe will have some blink, but its ok for now

I'll try, perhaps an additional deletion shortcut key is needed, and it is not possible to enter deletion mode by pressing d on the original interface because it calls a callback every time it reads a string using getchar, after that, it will close all windows.

**Comment by otavioschwanck** [comment]
> > > I tried using the callback of portal's context directly to delete the bookmark, which can achieve deletion but without any visual effect. The deleted window will still be displayed. Implementing the delete mode in portal ui may require changing portal's API, or should we have the same look as files for managing bookmarks(portal only for jumping)?
> > 
> > 
> > we could just refresh the portal after deleting something (close and open again). Maybe will have some blink, but its ok for now
> 
> I'll try, perhaps an additional deletion shortcut key is needed, and it is not possible to enter deletion mode by pressing d on the original interface because it calls a callback every time it reads a string using getchar, after that, it will close all windows.

in the weekend i will try to think for a solution to the delete mode, but it is looking good already

**Pull request merged**
